[package]
name = "pdfium-render"
version = "0.7.26"
edition = "2018"
publish = true
description = "A high-level idiomatic Rust wrapper around Pdfium, the C++ PDF library used by the Google Chromium project."
readme = "README.md"
homepage = "https://github.com/ajrcarey/pdfium-render"
repository = "https://github.com/ajrcarey/pdfium-render"
license = "MIT OR Apache-2.0"
keywords = ["pdf", "pdfium"]
categories = ["api-bindings", "multimedia::images", "visualization", "wasm"]
authors = ["Alastair Carey <alastair@duetto.dev>"]

[lib]
name = "pdfium_render"
crate-type = ["lib", "staticlib", "cdylib"]
doctest = false

[dependencies]
bitflags = "^1"
bytes = "^1"
image = ">= 0.24.0" # DynamicImage trait definitions changed between 0.23.14 and 0.24.0; we use trait from version 0.24.0 and later.
iter_tools = "^0.1"
lazy_static = "^1"
log = "^0.4"
maybe-owned = "^0.3"
utf16string = "^0.2"
vecmath = "^1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "^0.2"
console_error_panic_hook = "^0.1"
js-sys = "^0.3"
wasm-bindgen = { version = "^0.2", features = ["enable-interning"] }
wasm-bindgen-futures = { version = "^0.4" }
web-sys = { version = "^0.3", features = ["TextDecoder", "ImageData", "Window", "Response", "Blob"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "^0.7"

[build-dependencies]
bindgen = { version = "^0" }

[dev-dependencies]
# Dependencies specific to examples. Dependencies for the WASM example in examples/wasm.rs
# are specified separately in examples/Cargo.toml.
rand = "^0" # Used by examples/create.rs
rayon = "^1" # Used by examples/thread_safe.rs

[features]
default = ["sync", "thread_safe"]
bindings = []
static = []
thread_safe = []
"libstdc++" = ["static"]
"libc++" = ["static"]
sync = ["thread_safe"]
