[package]
name = "pdfium-render"
version = "0.5.1"
edition = "2018"
publish = true
description = "A high-level idiomatic Rust wrapper around Pdfium, the C++ PDF library used by the Google Chromium project."
readme = "README.md"
homepage = "https://github.com/ajrcarey/pdfium-render"
repository = "https://github.com/ajrcarey/pdfium-render"
license = "MIT OR Apache-2.0"
keywords = ["pdf", "pdfium"]
categories = ["api-bindings", "multimedia::images", "visualization", "wasm"]
authors = ["Alastair Carey <alastair@duetto.dev>"]

[lib]
name = "pdfium_render"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
image = "^0"
log = "^0"
bytes = "^1"
utf16string = "^0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "^0"
js-sys = "^0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "^0"

[build-dependencies]
bindgen = { version = "^0" }
