[package]
name = "pdfium-render"
version = "0.7.0"
edition = "2018"
publish = true
description = "A high-level idiomatic Rust wrapper around Pdfium, the C++ PDF library used by the Google Chromium project."
readme = "README.md"
homepage = "https://github.com/ajrcarey/pdfium-render"
repository = "https://github.com/ajrcarey/pdfium-render"
license = "MIT OR Apache-2.0"
keywords = ["pdf", "pdfium"]
categories = ["api-bindings", "multimedia::images", "visualization", "wasm"]
authors = ["Alastair Carey <alastair@duetto.dev>"]

[lib]
name = "pdfium_render"
crate-type = ["lib", "staticlib", "cdylib"]
doctest = false

[dependencies]
bitflags = "^1"
bytes = "^1"
image = "^0"
log = "^0"
utf16string = "^0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "^0", features = ["enable-interning"] }
wasm-bindgen-futures = { version = "^0" }
js-sys = "^0"
web-sys = { version = "^0", features = ["TextDecoder", "ImageData", "Window", "Response", "Blob"] }
lazy_static = "^1"
console_log = "^0"
console_error_panic_hook = "^0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "^0"

[build-dependencies]
bindgen = { version = "^0" }

[dev-dependencies]
# Dependencies specific to examples.
# Note that dependencies for the WASM example in examples/wasm.rs are specified separately
# in examples/Cargo.toml.

rand = "^0" # Used by examples/create.rs


[features]
default = []
bindings = []
static = []
